### PR TITLE
Enabling user to set a logger instance on the config file

### PR DESCRIPTION
**Pull request by bravewood**
# What's this PR

Since we couldn't control settings of the logger in detail, as the logger is set in a internal method of Dispatcher.php.
I'd like to set a logger instance on the config file, so that we can set  a formatter or other setting of a logger.
This PR allows user to set a logger instance on the config file.

This is a sample of config.
Just add a 'logger' key and a logger instance as a value.

```
    'logger' => [
        'logger' => new \Monolog\Logger('app',
            [
                (new \Monolog\Handler\StreamHandler(
                    '/path/to/your.log',
                    \Monolog\Logger::DEBUG
                ))->setFormatter(new \Monolog\Formatter\JsonFormatter())
            ]
        ),
    ],
```
# Break BC ?

**no**

You can still use the original setting like this.

```
    'logger' => [
        'path' =>  '/path/to/your.log',
        'level' => \Monolog\Logger::DEBUG,
    ],
```

### CODE REVIEW

**Comment by YuiSakamoto** [comment]
Test has failed  by this commit.
https://github.com/mercari/dietcube/commit/a51e59a3d230cad04d50e62e45a1b413f718268e
i don't know why...

**Comment by DQNEO** [comment]
I think I fixed it by #13 
Please merge master to this PR.

**Comment by bravewood** [comment]
@DQNEO Thanks for your advice! I just merged master branch and then the test has passed successfully.

@sotarok Please take a look at this PR. Kindly please let me know, if you have any questions or concerns. 
Thanks,

**Comment by DQNEO** [comment]
:+1:

**Comment by YuiSakamoto** [comment]
👍

**Comment by sotarok** [comment]
Set logger instance in the config file is not a good design I think.
How about move `createLogger()` from `Dispatcher` to `Application` instead.
Then it is overridable by application.
(Of course, the timing for the creating `Logger` also should be changed. Should be moved to just after `Application` instance created.)

**Comment by bravewood** [comment]
I just close this PR and open new one, since the initial topic is not suite to the last discussion.
Thanks!

**Pull request closed without merging**
