### PR TITLE
add php7.2 to travis.yml

### PR DESCRIPTION
**Pull request by DQNEO**
depends on https://github.com/mercari/dietcube/pull/27
php7.2 will soon be released.

### CODE REVIEW

**Comment by DQNEO** [comment]
I've found that php-cs-fixer conflicts with this... :thinking:

**Comment by DQNEO** [comment]
I'll retry later. close for now.

**Comment by DQNEO** [comment]
I reopen this.
After https://github.com/mercari/dietcube/pull/27 is merged, CI of this PR will success.

**Comment by suzuki** [comment]
The tests with PHP7.2 on Travis CI have many warnings:
https://travis-ci.org/mercari/dietcube/jobs/295615853

@DQNEO what do you think about it?

**Comment by DQNEO** [comment]
oh thanks for pointing it out.
I’ll investigate it later.

**Comment by DQNEO** [comment]
I re-run it and it looks passed.
https://travis-ci.org/mercari/dietcube/jobs/295615853
@suzuki Could you check it please?

**Review by suzuki — APPROVED** [review]

**Pull request merged**
